# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-24 15:18
from __future__ import unicode_literals

from django.db import migrations
import easy_thumbnails.fields


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='image',
            field=easy_thumbnails.fields.ThumbnailerImageField(upload_to=''),
        ),
    ]
